import { NotifierOptions } from 'angular-notifier';

export const notifierOptions: NotifierOptions = {
    position: {
      horizontal: {
        position: 'right',
        distance: 12
      },
      vertical: {
        position: 'top',
        distance: 12,
        gap: 10
      }
    },
    theme: 'material',
    behaviour: {
      autoHide: 5000,
      onClick: false,
      onMouseover: 'pauseAutoHide',
      showDismissButton: true,
      stacking: 4
    },
    animations: {
      enabled: true,
      show: {
        preset: 'slide',
        speed: 300,
        easing: 'ease'
      },
      hide: {
        preset: 'slide',
        speed: 300,
        easing: 'ease',
        offset: 50
      },
      shift: {
        speed: 300,
        easing: 'ease'
      },
      overlap: 150
    }
  };

  export const UFS = [
    { value:"AC", label: "Acre" },
    { value:"AL", label: "Alagoas" },
    { value:"AM", label: "Amazonas" },
    { value:"AP", label: "Amapá" },
    { value:"BA", label: "Bahia" },
    { value:"CE", label: "Ceará" },
    { value:"DF", label: "Distrito Federal" },
    { value:"ES", label: "Espírito Santo" },
    { value:"GO", label: "Goiás" },
    { value:"MA", label: "Maranhão" },
    { value:"MT", label: "Mato Grosso" },
    { value:"MS", label: "Mato Grosso do Sul" },
    { value:"MG", label: "Minas Gerais" },
    { value:"PA", label: "Pará" },
    { value:"PB", label: "Paraíba" },
    { value:"PR", label: "Paraná" },
    { value:"PE", label: "Pernambuco" },
    { value:"PI", label: "Piauí" },
    { value:"RJ", label: "Rio de Janeiro" },
    { value:"RN", label: "Rio Grande do Norte" },
    { value:"RO", label: "Rondônia" },
    { value:"RS", label: "Rio Grande do Sul" },
    { value:"RR", label: "Roraima" },
    { value:"SC", label: "Santa Catarina" },
    { value:"SE", label: "Sergipe" },
    { value:"SP", label: "São Paulo" },
    { value:"TO", label: "Tocantins" }
  ];

  export const OCCUPATIONS = [
    { value: 1, label: "Empregado"},
    { value: 2, label: "Empresário"},
    { value: 3, label: "Servidor Público"},
    { value: 4, label: "Aposentado"},
    { value: 5, label: "Autônomo"},
    { value: 6, label: "Desempregado"},
    { value: 7, label: "Estudante"},
    { value: 8, label: "Não Cadastrado"},
    { value: 9, label: "Profissional liberal"},
  ];

  export const GENDERS = [
    {value: "M", label: "Masculino"},
    {value: "F", label: "Feminino"}
  ];
  // export const banks = [
  //   { value: "", label: "Nome do Banco" },
  //   { value: "1", label: "ABC Brasil S.A." },
  //   { value: "2", label: "ABN AMRO Real S.A." },
  //   { value: "3", label: "Alfa S.A." },
  //   { value: "4", label: "Alvorada S.A." },
  //   { value: "5", label: "Banerj S.A." },
  //   { value: "6", label: "Banestado S.A." },
  //   { value: "7", label: "Barclays S.A." },
  //   { value: "8", label: "BBM S.A." },
  //   { value: "9", label: "Beg S.A." },
  //   { value: "10", label: "Bem S.A." },
  //   { value: "11", label: "BM&amp;F de Serviços de Liquidação e Custódia S.A" },
  //   { value: "12", label: "BMC S.A." },
  //   { value: "13", label: "BMG S.A." },
  //   { value: "14", label: "BNP Paribas Brasil S.A." },
  //   { value: "15", label: "Boavista Interatlântico S.A." },
  //   { value: "16", label: "Bradesco S.A." },
  //   { value: "17", label: "Brascan S.A." },
  //   { value: "18", label: "Cacique S.A." },
  //   { value: "19", label: "Calyon Brasil S.A." },
  //   { value: "20", label: "Cargill S.A." },
  //   { value: "21", label: "Citibank S.A." },
  //   { value: "22", label: "Comercial e de Investimento Sudameris S.A." },
  //   { value: "23", label: "Cooperativo do Brasil S.A. – BANCOOB" },
  //   { value: "24", label: "Cooperativo Sicredi S.A. – BANSICREDI" },
  //   { value: "25", label: "Credit Suisse (Brasil) S.A." },
  //   { value: "26", label: "Cruzeiro do Sul S.A." },
  //   { value: "27", label: "Banco da Amazônia S.A." },
  //   { value: "28", label: "Daycoval S.A." },
  //   { value: "29", label: "Banco de Pernambuco S.A. – BANDEPE" },
  //   { value: "30", label: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A." },
  //   { value: "31", label: "Dibens S.A." },
  //   { value: "32", label: "Banco do Brasil S.A." },
  //   { value: "33", label: "Banco do Estado de Santa Catarina S.A." },
  //   { value: "34", label: "Banco do Estado de Sergipe S.A." },
  //   { value: "35", label: "Banco do Estado do Pará S.A." },
  //   { value: "36", label: "Banco do Estado do Rio Grande do Sul S.A." },
  //   { value: "37", label: "Banco do Nordeste do Brasil S.A." },
  //   { value: "38", label: "Fator S.A." },
  //   { value: "39", label: "Fibra S.A." },
  //   { value: "40", label: "Finasa S.A." },
  //   { value: "41", label: "Fininvest S.A." },
  //   { value: "42", label: "GE Capital S.A." },
  //   { value: "43", label: "Gerdau S.A." },
  //   { value: "44", label: "Guanabara S.A." },
  //   { value: "45", label: "Ibi S.A. Banco Múltiplo" },
  //   { value: "46", label: "Industrial do Brasil S.A." },
  //   { value: "47", label: "Industrial e Comercial S.A." },
  //   { value: "48", label: "Indusval S.A." },
  //   { value: "49", label: "Intercap S.A." },
  //   { value: "50", label: "Investcred Unibanco S.A." },
  //   { value: "51", label: "Itaú S.A." },
  //   { value: "52", label: "J. P. Morgan S.A." },
  //   { value: "53", label: "J. Safra S.A." },
  //   { value: "54", label: "Luso Brasileiro S.A." },
  //   { value: "55", label: "Mercantil de São Paulo S.A." },
  //   { value: "56", label: "Mercantil do Brasil S.A." },
  //   { value: "57", label: "Merrill Lynch de Investimentos S.A." },
  //   { value: "58", label: "Nossa Caixa S.A." },
  //   { value: "59", label: "Opportunity S.A." },
  //   { value: "60", label: "Panamericano S.A." },
  //   { value: "61", label: "Paulista S.A." },
  //   { value: "62", label: "Pine S.A." },
  //   { value: "63", label: "Prosper S.A." },
  //   { value: "64", label: "Rabobank International Brasil S.A." },
  //   { value: "65", label: "Rendimento S.A." },
  //   { value: "66", label: "Rural Mais S.A." },
  //   { value: "67", label: "Rural S.A." },
  //   { value: "68", label: "Safra S.A." },
  //   { value: "69", label: "Santander" },
  //   { value: "70", label: "Schahin S.A." },
  //   { value: "71", label: "Simples S.A." },
  //   { value: "72", label: "Société Générale Brasil S.A." },
  //   { value: "73", label: "Sofisa S.A." },
  //   { value: "74", label: "Sudameris Brasil S.A." },
  //   { value: "75", label: "Sumitomo Mitsui Brasileiro S.A." },
  //   { value: "76", label: "Triângulo S.A." },
  //   { value: "77", label: "UBS Pactual S.A." },
  //   { value: "78", label: "UBS S.A." },
  //   { value: "79", label: "Único S.A." },
  //   { value: "80", label: "Votorantim S.A." },
  //   { value: "81", label: "VR S.A." },
  //   { value: "82", label: "WestLB do Brasil S.A." },
  //   { value: "83", label: "BANESTES S.A. Banco do Estado do Espírito Santo" },
  //   { value: "84", label: "Banif-Banco Internacional do Funchal (Brasil)S.A." },
  //   { value: "85", label: "Bankpar Banco Multiplo S.A." },
  //   { value: "86", label: "BRB – Banco de Brasília S.A." },
  //   { value: "87", label: "CEF" },
  //   { value: "88", label: "Citibank N.A." },
  //   { value: "89", label: "Deutsche Bank S.A. – Banco Alemão" },
  //   { value: "90", label: "Dresdner Bank Brasil S.A. – Banco Múltiplo" },
  //   { value: "91", label: "Dresdner Bank Lateinamerika Aktiengesellschaft" },
  //   { value: "92", label: "Hipercard Banco Múltiplo S.A." },
  //   { value: "93", label: "HSBC" },
  //   { value: "94", label: "ING Bank N.V." },
  //   { value: "95", label: "JPMorgan Chase Bank" },
  //   { value: "96", label: "Lemon Bank Banco Múltiplo S.A." },
  //   { value: "97", label: "UNIBANCO – União de bancos Brasileiros S.A." },
  //   { value: "98", label: "Unicard Banco Múltiplo S.A." },
  //   { value: "99", label: "CECRED" },
  //   { value: "100", label: "UNICRED" },
  //   { value: "101", label: "BB Banco Popular do Brasil S.A." },
  //   { value: "102", label: "BPN Brasil Banco Mútiplo S.A." },
  //   { value: "103", label: "Caixa Econômica Federal S.A." },
  //   { value: "104", label: "Sicoob" },
  //   { value: "105", label: "Banco Original S.A." },
  //   { value: "106", label: "Banco Intermedium S.A." },
  //   { value: "107", label: "Nu Pagamentos S.A." },
  //   { value: "108", label: "Cresol" },
  //   { value: "109", label: "Banco do Estado do Pará S. A." }
  // ];